# Generated by Django 3.1.6 on 2021-02-20 01:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Name')),
                ('body_text', models.CharField(default='', max_length=50000, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Consent Form',
                'verbose_name_plural': 'Consent Forms',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactEmail', models.CharField(default='JohnSmith@abc.edu', max_length=1000)),
                ('experimentTimeZone', models.CharField(default='US/Pacific', max_length=1000)),
                ('siteURL', models.CharField(default='https://www.google.com/', max_length=200)),
                ('test_email_account', models.CharField(default='', max_length=1000)),
                ('invitation_text_subject', models.CharField(default='', max_length=1000)),
                ('invitation_text', models.CharField(default='', max_length=10000)),
                ('cancelation_text_subject', models.CharField(default='', max_length=1000)),
                ('cancelation_text', models.CharField(default='', max_length=10000)),
                ('questionnaire1Required', models.BooleanField(default=True)),
                ('questionnaire2Required', models.BooleanField(default=True)),
                ('staffsessionHelpText', models.CharField(default='', max_length=5000)),
                ('staffHomeHelpText', models.CharField(default='', max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parameters',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='ParameterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_form_required', models.BooleanField(default=True)),
                ('number_of_periods', models.IntegerField(default=1)),
                ('number_of_subjects', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consent_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.consentforms')),
            ],
            options={
                'verbose_name': 'Study Parameter Set',
                'verbose_name_plural': 'Study Parameter Sets',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='*** New Session ***', max_length=300)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('started', models.BooleanField(default=False)),
                ('current_period', models.IntegerField(default=0)),
                ('canceled', models.BooleanField(default=False)),
                ('cancelation_text', models.CharField(default='', max_length=10000)),
                ('cancelation_text_subject', models.CharField(default='', max_length=1000)),
                ('invitations_sent', models.BooleanField(default=False)),
                ('invitation_text', models.CharField(default='', max_length=10000)),
                ('invitation_text_subject', models.CharField(default='', max_length=1000)),
                ('soft_delete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Experiment Session',
                'verbose_name_plural': 'Experiment Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(null=True, verbose_name='ID Number in Session')),
                ('login_key', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Login Key')),
                ('name', models.CharField(default='Subject Name', max_length=300, verbose_name='Subject Name')),
                ('contact_email', models.CharField(default='panther@chapman.edu', max_length=300, verbose_name='Subject Email')),
                ('student_id', models.CharField(default='123456789', max_length=300, verbose_name='Student ID Number')),
                ('consent_required', models.BooleanField(default=True, verbose_name='Consent Form Signed')),
                ('consent_signature', models.CharField(default='', max_length=300, verbose_name='Consent Form Signature')),
                ('questionnaire1_required', models.BooleanField(default=True, verbose_name='Pre-questionnaire Complete')),
                ('questionnaire2_required', models.BooleanField(default=True, verbose_name='Post-questionnaire Complete')),
                ('display_color', models.CharField(default='#000000', max_length=300, verbose_name='Graph Color')),
                ('soft_delete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_subjects', to='main.session')),
            ],
            options={
                'verbose_name': 'Session Subject',
                'verbose_name_plural': 'Session Subjects',
            },
        ),
        migrations.CreateModel(
            name='SessionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_key', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Login Key')),
                ('period_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_periods', to='main.session')),
            ],
            options={
                'verbose_name': 'Session Day',
                'verbose_name_plural': 'Session Days',
            },
        ),
        migrations.AddConstraint(
            model_name='sessionsubject',
            constraint=models.UniqueConstraint(fields=('id_number', 'session'), name='Session_subject'),
        ),
        migrations.AddConstraint(
            model_name='sessionperiod',
            constraint=models.UniqueConstraint(fields=('session', 'period_number'), name='unique_SD'),
        ),
    ]
