# Generated by Django 3.1.6 on 2021-02-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='questionnaire1Required',
            new_name='consent_form_required',
        ),
        migrations.RenameField(
            model_name='parameters',
            old_name='contactEmail',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='parameters',
            old_name='experimentTimeZone',
            new_name='experiment_time_zone',
        ),
        migrations.RenameField(
            model_name='parameters',
            old_name='questionnaire2Required',
            new_name='questionnaire1_required',
        ),
        migrations.RenameField(
            model_name='parameters',
            old_name='siteURL',
            new_name='site_url',
        ),
        migrations.RenameField(
            model_name='parameters',
            old_name='staffsessionHelpText',
            new_name='staff_home_help_text',
        ),
        migrations.RenameField(
            model_name='parameters',
            old_name='staffHomeHelpText',
            new_name='staff_session_help_text',
        ),
        migrations.AddField(
            model_name='parameters',
            name='questionnaire2_required',
            field=models.BooleanField(default=True),
        ),
    ]
