# Generated by Django 3.1.6 on 2021-02-23 05:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210220_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='channel_key',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Channel Key'),
        ),
    ]
