# Generated by Django 3.1.6 on 2021-03-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210223_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Period Number')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parameter Set Period',
                'verbose_name_plural': 'Parameter Set Periods',
            },
        ),
        migrations.AlterModelOptions(
            name='parameterset',
            options={'verbose_name': 'Experiment Parameter Set', 'verbose_name_plural': 'Experiment Parameter Sets'},
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='number_of_subjects',
        ),
        migrations.CreateModel(
            name='ParameterSetPeriodSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(null=True, verbose_name='ID Number in Session')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_period_subjects', to='main.parametersetperiod')),
            ],
            options={
                'verbose_name': 'Study Parameter Set Subject',
                'verbose_name_plural': 'Study Parameter Sets Subjets',
            },
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='parameter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_periods', to='main.parameterset'),
        ),
        migrations.AddConstraint(
            model_name='parametersetperiodsubject',
            constraint=models.UniqueConstraint(fields=('parameter_set_period', 'id_number'), name='unique_PSPS'),
        ),
        migrations.AddConstraint(
            model_name='parametersetperiod',
            constraint=models.UniqueConstraint(fields=('parameter_set', 'number'), name='unique_PSP'),
        ),
    ]
