# Generated by Django 3.1.6 on 2021-05-06 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210223_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField(null=True, verbose_name='Period number')),
                ('id_number', models.IntegerField(null=True, verbose_name='ID Number in Period')),
                ('subject_type', models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Buyer', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_subjects', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameters for Subject',
                'verbose_name_plural': 'Parameters for Subjects',
            },
        ),
        migrations.RemoveField(
            model_name='session',
            name='cancelation_text',
        ),
        migrations.RemoveField(
            model_name='session',
            name='cancelation_text_subject',
        ),
        migrations.RemoveField(
            model_name='session',
            name='canceled',
        ),
        migrations.AddField(
            model_name='session',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ParameterSetSubjectValuecost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_subject_valuecosts', to='main.parametersetsubject')),
            ],
            options={
                'verbose_name': 'Value or cost',
                'verbose_name_plural': 'Value or costs',
            },
        ),
        migrations.AddConstraint(
            model_name='parametersetsubject',
            constraint=models.UniqueConstraint(fields=('parameter_set', 'period_number', 'id_number', 'subject_type'), name='unique_subject_for_period'),
        ),
    ]
