# Generated by Django 3.1.6 on 2021-03-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210308_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='number_of_periods',
        ),
    ]
