# Generated by Django 3.2.2 on 2021-05-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210506_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='number_of_subjects',
        ),
        migrations.AddField(
            model_name='parameterset',
            name='number_of_buyers',
            field=models.IntegerField(default=1, verbose_name='Number of buyers'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='number_of_sellers',
            field=models.IntegerField(default=1, verbose_name='Number of sellers'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='number_of_periods',
            field=models.IntegerField(default=1, verbose_name='Number of periods'),
        ),
    ]
