# Generated by Django 3.1.6 on 2021-03-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_parameterset_number_of_periods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['title'], 'verbose_name': 'Experiment Session', 'verbose_name_plural': 'Experiment Sessions'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_date',
        ),
    ]
