# Generated by Django 3.1.6 on 2021-03-09 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210308_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiodsubject',
            name='subject_type',
            field=models.CharField(choices=[('Both', 'Both'), ('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Both', max_length=100),
        ),
        migrations.CreateModel(
            name='ParameterSetPeriodSubjectValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_period_subject_values', to='main.parametersetperiodsubject')),
            ],
            options={
                'verbose_name': 'Parameter Set Subject Value',
                'verbose_name_plural': 'Parameter Sets Subjet Values',
            },
        ),
    ]
