# Generated by Django 3.2.2 on 2021-05-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210511_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetsubject',
            name='id_number',
            field=models.IntegerField(default=1, verbose_name='ID Number in Period'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametersetsubject',
            name='period_number',
            field=models.IntegerField(default=1, verbose_name='Period number'),
            preserve_default=False,
        ),
    ]
