# Generated by Django 3.1.6 on 2021-03-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210309_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiodsubject',
            name='inventory',
            field=models.IntegerField(default=1, verbose_name='Number of units held'),
        ),
        migrations.AlterField(
            model_name='parametersetperiodsubject',
            name='id_number',
            field=models.IntegerField(default=1, verbose_name='ID Number in Session'),
        ),
    ]
