# Generated by Django 3.2.2 on 2021-05-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210511_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetsubject',
            options={'ordering': ['id_number'], 'verbose_name': 'Parameters for Subject', 'verbose_name_plural': 'Parameters for Subjects'},
        ),
    ]
