# Generated by Django 3.1.6 on 2021-03-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210309_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetperiodsubjectvalue',
            old_name='parameter_set_period',
            new_name='parameter_set_period_subject',
        ),
        migrations.AlterField(
            model_name='parametersetperiodsubject',
            name='subject_type',
            field=models.CharField(choices=[('Both', 'Both'), ('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Both', max_length=100, verbose_name='Type of participant'),
        ),
    ]
