# Generated by Django 3.2.2 on 2021-05-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210518_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetperiod',
            name='parameter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_periods', to='main.parameterset'),
        ),
    ]
