# Generated by Django 3.1.6 on 2021-03-09 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210309_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParameterSetPeriodSubjectValue',
            new_name='ParameterSetPeriodSubjectValuecost',
        ),
        migrations.RenameField(
            model_name='parametersetperiodsubjectvaluecost',
            old_name='value',
            new_name='value_cost',
        ),
    ]
