# Generated by Django 3.1.6 on 2021-03-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210309_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetperiodsubject',
            name='inventory',
        ),
        migrations.AlterField(
            model_name='parametersetperiodsubject',
            name='subject_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Buyer', max_length=100, verbose_name='Type of participant'),
        ),
    ]
