# Generated by Django 3.2.2 on 2021-05-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_parametersetperiod_parameter_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetperiodsubjectvaluecost',
            old_name='parameter_set_subject',
            new_name='parameter_set_period_subject',
        ),
    ]
