# Generated by Django 3.2.2 on 2021-05-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_parameter_set_subject_parametersetperiodsubjectvaluecost_parameter_set_period_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='number_of_periods',
        ),
    ]
