# Generated by Django 3.2.2 on 2021-05-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_parameterset_number_of_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiodsubjectvaluecost',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='parametersetperiodsubjectvaluecost',
            name='value_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Value or Cost'),
        ),
    ]
