# Generated by Django 3.2.2 on 2021-05-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210519_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetperiodsubjectvaluecost',
            options={'ordering': ['enabled'], 'verbose_name': 'Value or cost', 'verbose_name_plural': 'Value or costs'},
        ),
    ]
