# Generated by Django 3.2.2 on 2021-05-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_parametersetperiodsubjectvaluecost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetperiodsubjectvaluecost',
            options={'verbose_name': 'Value or cost', 'verbose_name_plural': 'Value or costs'},
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='price_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price Cap'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='price_cap_enabled',
            field=models.BooleanField(default=False, verbose_name='Price Cap Enabled'),
        ),
    ]
