# Generated by Django 3.2.2 on 2021-06-03 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210528_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='x_scale_max',
            field=models.IntegerField(default=10, verbose_name='X Scale Max'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='y_scale_max',
            field=models.IntegerField(default=10, verbose_name='Y Scale Max'),
            preserve_default=False,
        ),
    ]
