# Generated by Django 3.2.2 on 2021-06-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210603_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetperiod',
            name='x_scale_max',
            field=models.IntegerField(default=10, verbose_name='X Scale Max'),
        ),
        migrations.AlterField(
            model_name='parametersetperiod',
            name='y_scale_max',
            field=models.IntegerField(default=10, verbose_name='Y Scale Max'),
        ),
    ]
