# Generated by Django 3.2.2 on 2021-06-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210612_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionperiod',
            options={'verbose_name': 'Session Period', 'verbose_name_plural': 'Session Periods'},
        ),
        migrations.RemoveField(
            model_name='sessionperiod',
            name='login_key',
        ),
    ]
