# Generated by Django 3.2.2 on 2021-06-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210618_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPeriodTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_period_trades', to='main.sessionperiod')),
            ],
            options={
                'verbose_name': 'Session Period Trade',
                'verbose_name_plural': 'Session Period Trades',
            },
        ),
        migrations.CreateModel(
            name='SessionPeriodTradeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_period_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_period_trade_offers', to='main.sessionperiodtrade')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_period_trade_offers_cost', to='main.parametersetperiodsubjectvaluecost')),
            ],
            options={
                'verbose_name': 'Session Period Trade Offer',
                'verbose_name_plural': 'Session Period Trade Offers',
            },
        ),
        migrations.CreateModel(
            name='SessionPeriodTradeBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_period_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_period_trade_bids', to='main.sessionperiodtrade')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_period_trade_bids_value', to='main.parametersetperiodsubjectvaluecost')),
            ],
            options={
                'verbose_name': 'Session Period Trade Bid',
                'verbose_name_plural': 'Session Period Trade Bids',
            },
        ),
        migrations.AddConstraint(
            model_name='sessionperiodtrade',
            constraint=models.UniqueConstraint(fields=('session_period', 'trade_number'), name='unique_SD_trade'),
        ),
    ]
