# Generated by Django 3.2.2 on 2021-06-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210619_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSubjectPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_unit_number', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Subject Period',
                'verbose_name_plural': 'Session Subject Periods',
            },
        ),
        migrations.AlterModelOptions(
            name='sessionperiodtradeoffer',
            options={'ordering': ['amount'], 'verbose_name': 'Session Period Trade Offer', 'verbose_name_plural': 'Session Period Trade Offers'},
        ),
        migrations.RemoveConstraint(
            model_name='sessionsubject',
            name='Session_subject',
        ),
        migrations.RemoveField(
            model_name='sessionsubject',
            name='consent_required',
        ),
        migrations.RemoveField(
            model_name='sessionsubject',
            name='consent_signature',
        ),
        migrations.RemoveField(
            model_name='sessionsubject',
            name='display_color',
        ),
        migrations.RemoveField(
            model_name='sessionsubject',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='sessionsubject',
            name='soft_delete',
        ),
        migrations.RemoveField(
            model_name='sessionsubject',
            name='student_id',
        ),
        migrations.AddField(
            model_name='sessionperiodtrade',
            name='buyer_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_period_trades_c', to='main.parametersetperiodsubjectvaluecost'),
        ),
        migrations.AddField(
            model_name='sessionperiodtrade',
            name='seller_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_period_trades_e', to='main.parametersetperiodsubjectvaluecost'),
        ),
        migrations.AlterField(
            model_name='sessionperiodtrade',
            name='session_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_period_trades_a', to='main.sessionperiod'),
        ),
        migrations.AddField(
            model_name='sessionsubjectperiod',
            name='parameter_set_period_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_subject_periods_c', to='main.parametersetperiodsubject'),
        ),
        migrations.AddField(
            model_name='sessionsubjectperiod',
            name='session_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_subject_periods_b', to='main.sessionperiod'),
        ),
        migrations.AddField(
            model_name='sessionsubjectperiod',
            name='session_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_subject_periods_a', to='main.sessionsubject'),
        ),
        migrations.AddField(
            model_name='sessionperiodtrade',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_period_trades_b', to='main.sessionsubjectperiod'),
        ),
        migrations.AddField(
            model_name='sessionperiodtrade',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_period_trades_d', to='main.sessionsubjectperiod'),
        ),
        migrations.AddConstraint(
            model_name='sessionsubjectperiod',
            constraint=models.UniqueConstraint(fields=('session_subject', 'session_period'), name='Session_subject_period'),
        ),
    ]
