# Generated by Django 3.2.2 on 2021-06-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210625_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsubject',
            name='id_number',
            field=models.IntegerField(default=1, verbose_name='ID Number in Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionsubject',
            name='subject_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Buyer', max_length=100),
        ),
    ]
