# Generated by Django 3.2.2 on 2021-06-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210626_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionperiodtradeoffer',
            old_name='value',
            new_name='cost',
        ),
    ]
