# Generated by Django 3.2.2 on 2021-06-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_value_sessionperiodtradeoffer_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionperiodtradebid',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Bid Amount'),
        ),
        migrations.AlterField(
            model_name='sessionperiodtradeoffer',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Offer Amount'),
        ),
    ]
