# Generated by Django 3.2.2 on 2021-07-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210629_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionperiod',
            options={'ordering': ['period_number'], 'verbose_name': 'Session Period', 'verbose_name_plural': 'Session Periods'},
        ),
    ]
