# Generated by Django 3.2.5 on 2021-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_sessionperiod_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiodtrade',
            name='trade_complete',
            field=models.BooleanField(default=True),
        ),
    ]
