# Generated by Django 3.2.5 on 2021-07-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_sessionperiodtrade_trade_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiodtrade',
            name='trade_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Trade Price'),
        ),
    ]
