# Generated by Django 3.2.5 on 2021-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_sessionperiodtrade_trade_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionperiodtrade',
            name='trade_complete',
            field=models.BooleanField(default=False),
        ),
    ]
