# Generated by Django 3.2.2 on 2021-07-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_sessionperiodtrade_trade_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
