# Generated by Django 3.2.2 on 2021-08-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_session_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionsubject',
            options={'ordering': ['subject_type', 'id_number'], 'verbose_name': 'Session Subject', 'verbose_name_plural': 'Session Subjects'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='invitation_text',
        ),
        migrations.RemoveField(
            model_name='session',
            name='invitation_text_subject',
        ),
        migrations.RemoveField(
            model_name='session',
            name='invitations_sent',
        ),
    ]
