# Generated by Django 3.2.2 on 2021-08-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210811_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='cancelation_text',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='cancelation_text_subject',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='consent_form_required',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='invitation_text',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='invitation_text_subject',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='questionnaire1_required',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='questionnaire2_required',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='staff_home_help_text',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='staff_session_help_text',
        ),
    ]
