# Generated by Django 3.2.5 on 2021-08-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210825_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='help_docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Title')),
                ('path', models.CharField(default='/', max_length=300, verbose_name='URL Path')),
                ('text', models.CharField(default='', max_length=10000, verbose_name='Help Doc Text')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Doc',
                'verbose_name_plural': 'Help Docs',
            },
        ),
        migrations.DeleteModel(
            name='ConsentForms',
        ),
    ]
