# Generated by Django 3.2.5 on 2021-08-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210827_1824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='help_docs',
            new_name='HelpDocs',
        ),
    ]
