# Generated by Django 3.2.5 on 2021-09-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_help_docs_helpdocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='price_cap_type',
            field=models.CharField(choices=[('Floor', 'Floor'), ('Ceiling', 'Ceiling')], default='Ceiling', max_length=100),
        ),
    ]
