# Generated by Django 3.2.7 on 2021-09-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_parametersetperiod_price_cap_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionperiodtrade',
            options={'ordering': ['-trade_number'], 'verbose_name': 'Session Period Trade', 'verbose_name_plural': 'Session Period Trades'},
        ),
    ]
