# Generated by Django 3.2.7 on 2022-08-12 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0039_alter_sessionperiodtrade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionperiodtrade',
            options={'ordering': ['trade_number'], 'verbose_name': 'Session Period Trade', 'verbose_name_plural': 'Session Period Trades'},
        ),
        migrations.AddField(
            model_name='session',
            name='collaborators',
            field=models.ManyToManyField(related_name='sessions_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
