# Generated by Django 4.0.7 on 2022-08-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20220812_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpdocs',
            name='path',
        ),
    ]
